import { LexemeInput } from "../../grammars/hpsg/lexicon/lexeme-input.js";

export const lexemeData: LexemeInput[] = [
    {
        type: "pn-lxm",
        form: "john",
        reln: "named John",
    },
    {
        type: "pn-lxm",
        form: "mary",
        reln: "named Mary",
    },
    {
        type: "pron-lxm",
        form: "i",
        case: "nom",
        agr: "1sing",
        per: "1st",
        num: "sg",
        index: "self",
        restr: [
            { reln: "speaker", arg1: "self" },
        ],
    },
    {
        type: "pron-lxm",
        form: "me",
        case: "acc",
        agr: "1sing",
        per: "1st",
        num: "sg",
        index: "self",
        restr: [
            { reln: "speaker", arg1: "self" },
        ],
    },
    {
        type: "pron-lxm",
        form: "you",
        case: "nom",
        agr: "agr-cat",
        per: "2nd",
        index: "self",
        restr: [
            { reln: "addressee", arg1: "self" },
        ],
    },
    {
        type: "pron-lxm",
        form: "you",
        case: "acc",
        agr: "agr-cat",
        per: "2nd",
        index: "self",
        restr: [
            { reln: "addressee", arg1: "self" },
        ],
    },
    {
        type: "pron-lxm",
        form: "we",
        case: "nom",
        agr: "plural",
        per: "1st",
        num: "pl",
        index: "group",
        restr: [
            { reln: "group", arg1: "group" },
            { reln: "speaker", arg1: "speaker" },
            { reln: "member", arg1: "group", arg2: "speaker" },
        ],
    },
    {
        type: "pron-lxm",
        form: "myself",
        agr: "1sing",
        per: "1st",
        num: "sg",
        mode: "ana",
    },
    {
        type: "pron-lxm",
        form: "yourself",
        agr: "agr-cat",
        per: "2nd",
        mode: "ana",
    },
    {
        type: "det-lxm",
        form: "a",
        count: "+",
    },
    {
        type: "det-lxm",
        form: "the",
    },
    {
        type: "cntn-lxm",
        singular: "girl",
        plural: "girls",
        reln: "girl",
    },
    {
        type: "cntn-lxm",
        singular: "telescope",
        plural: "telescopes",
        reln: "telescope",
    },
    {
        type: "massn-lxm",
        form: "water",
        reln: "water",
    },
    {
        type: "siv-lxm",
        base: "walk",
        thirdSingular: "walks",
        presentParticiple: "walking",
        pastTense: "walked",
        pastParticiple: "walked",
        reln: "walk",
    },
    {
        type: "piv-lxm",
        base: "go",
        thirdSingular: "goes",
        presentParticiple: "going",
        pastTense: "went",
        pastParticiple: "gone",
        reln: "go",
        prepositionForm: "to-form",
    },
    {
        type: "stv-lxm",
        base: "see",
        thirdSingular: "sees",
        presentParticiple: "seeing",
        pastTense: "saw",
        pastParticiple: "seen",
        reln: "see",
    },
    {
        type: "dtv-lxm",
        base: "send",
        thirdSingular: "sends",
        presentParticiple: "sending",
        pastTense: "sent",
        pastParticiple: "sent",
        reln: "send",
    },
    {
        type: "ptv-lxm",
        base: "send",
        thirdSingular: "sends",
        presentParticiple: "sending",
        pastTense: "sent",
        pastParticiple: "sent",
        reln: "send",
        prepositionForm: "to-form",
    },
];
